# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
    volumes:
      - /Users/bhavesh/Documents/magento-environment/mysql/data:/var/lib/mysql
    networks:
      - mysql


  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

networks:
  mysql:
    driver: bridge